#!/usr/bin/env bash
# Installs the OpenCode engineering team into Google Antigravity.
#
# Regenerates the six native Antigravity agent.md files (see
# scripts/sync-antigravity-agents.mjs) and symlinks each
# .agents/agents/oc-<role>/ directory to
# ~/.gemini/config/agents/oc-<role>/, Antigravity's global-scoped custom
# agent discovery path (each agent MUST live in its own dedicated
# subdirectory there — see antigravity/README.md). It also creates symlinks
# from ~/.gemini/skills/engineering-team/ and
# ~/.gemini/rules/engineering-team.md to the corresponding files in this
# repo, so the repo stays the single source of truth. It also mirrors every
# directory under .claude/skills/ (delegate-first, java, kafka, ...) into
# ~/.gemini/skills/<name>/, so any skill added there is picked up here too
# without a second script to maintain.
#
# Safe to re-run. Existing symlinks are refreshed; real directories are
# never overwritten.
#
# Usage:
#   antigravity/install.sh [--dry-run] [--uninstall]

set -euo pipefail
shopt -s nullglob

DRY_RUN=0
UNINSTALL=0

usage() {
  cat <<'USAGE'
Usage: antigravity/install.sh [--dry-run] [--uninstall]

  --dry-run     Print every action; do nothing.
  --uninstall   Remove the symlinks (does not touch the repo).
  -h, --help    Show this help.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)   DRY_RUN=1;   shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -h|--help)   usage; exit 0 ;;
    *)
      echo "antigravity/install.sh: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd)"
TIMESTAMP="$(date +%Y%m%d%H%M%S)"

GEMINI_DIR="$HOME/.gemini"
SKILLS_DIR="$GEMINI_DIR/skills"
RULES_DIR="$GEMINI_DIR/rules"
AGENTS_DIR="$GEMINI_DIR/config/agents"

SKILL_SRC="$REPO_ROOT/antigravity/skill"
RULES_SRC="$REPO_ROOT/antigravity/rules/engineering-team.md"
AGENTS_SRC_DIR="$REPO_ROOT/.agents/agents"

SKILL_TARGET="$SKILLS_DIR/engineering-team"
RULES_TARGET="$RULES_DIR/engineering-team.md"

# Every directory under .claude/skills/ — the shared skill source for
# OpenCode and Claude Code (see docs/adding-a-skill.md) — gets mirrored
# into ~/.gemini/skills/<name>/ too. This is IN ADDITION to the hardcoded
# engineering-team skill above, which is Antigravity-specific and not
# sourced from .claude/skills/.
CLAUDE_SKILLS_SRC_DIR="$REPO_ROOT/.claude/skills"

# The six native Antigravity agent directories generated by
# scripts/sync-antigravity-agents.mjs from agents/*.md (see
# scripts/lib/team.mjs for the roster this must stay in sync with).
OC_AGENT_NAMES=(oc-tech-lead oc-senior-dev oc-implementer oc-boilerplate oc-code-reviewer oc-debugger)

log() { printf '%s\n' "$*"; }

act() {
  local desc="$1"; shift
  if [ "$DRY_RUN" = "1" ]; then
    log "[dry-run] would: $desc"
  else
    log "-> $desc"
    "$@"
  fi
}

# ---- Uninstall mode ----
if [ "$UNINSTALL" = "1" ]; then
  if [ -L "$SKILL_TARGET" ]; then
    act "remove symlink $SKILL_TARGET" rm "$SKILL_TARGET"
  elif [ -e "$SKILL_TARGET" ]; then
    log "WARNING: $SKILL_TARGET is not a symlink — skipping."
  else
    log "$SKILL_TARGET does not exist — nothing to remove."
  fi

  if [ -L "$RULES_TARGET" ]; then
    act "remove symlink $RULES_TARGET" rm "$RULES_TARGET"
  elif [ -e "$RULES_TARGET" ]; then
    log "WARNING: $RULES_TARGET is not a symlink — skipping."
  else
    log "$RULES_TARGET does not exist — nothing to remove."
  fi

  # Remove the generalized .claude/skills/* mirror symlinks too — only the
  # ones this script would have created (a real, non-symlink directory is
  # never touched).
  for skill_src in "$CLAUDE_SKILLS_SRC_DIR"/*/; do
    skill_name="$(basename "$skill_src")"
    skill_target="$SKILLS_DIR/$skill_name"
    if [ -L "$skill_target" ]; then
      act "remove symlink $skill_target" rm "$skill_target"
    elif [ -e "$skill_target" ]; then
      log "WARNING: $skill_target is not a symlink — skipping."
    else
      log "$skill_target does not exist — nothing to remove."
    fi
  done

  # Remove the six oc-<role> agent.md symlinks too — same warn-and-skip
  # behavior for anything that isn't a symlink this script created.
  for agent_name in "${OC_AGENT_NAMES[@]}"; do
    agent_target="$AGENTS_DIR/$agent_name"
    if [ -L "$agent_target" ]; then
      act "remove symlink $agent_target" rm "$agent_target"
    elif [ -e "$agent_target" ]; then
      log "WARNING: $agent_target is not a symlink — skipping."
    else
      log "$agent_target does not exist — nothing to remove."
    fi
  done

  log ""
  log "antigravity/install.sh: uninstall done (dry-run=$DRY_RUN)."
  exit 0
fi

# ---- Install mode ----

# 0. Regenerate the six native Antigravity agent.md files from agents/*.md
#    so what gets symlinked below is always current (mirrors how
#    scripts/install.sh's claude step regenerates before symlinking).
if [ "$DRY_RUN" = "1" ]; then
  log "[dry-run] would: node scripts/sync-antigravity-agents.mjs"
else
  log "-> node scripts/sync-antigravity-agents.mjs"
  node "$REPO_ROOT/scripts/sync-antigravity-agents.mjs"
fi

# 1. Ensure target directories exist
act "ensure $SKILLS_DIR exists" mkdir -p "$SKILLS_DIR"
act "ensure $RULES_DIR exists"  mkdir -p "$RULES_DIR"
act "ensure $AGENTS_DIR exists" mkdir -p "$AGENTS_DIR"

# 2. Symlink the skill directory
if [ -L "$SKILL_TARGET" ]; then
  # $1/$2 must expand inside the bash -c subshell, not the parent shell.
  # shellcheck disable=SC2016
  act "refresh symlink $SKILL_TARGET -> $SKILL_SRC" bash -c \
    'rm "$1" && ln -s "$2" "$1"' _ "$SKILL_TARGET" "$SKILL_SRC"
elif [ -e "$SKILL_TARGET" ]; then
  log "WARNING: $SKILL_TARGET exists and is not a symlink — backing up."
  act "backup $SKILL_TARGET" mv "$SKILL_TARGET" "$SKILL_TARGET.bak.$TIMESTAMP"
  act "symlink $SKILL_TARGET -> $SKILL_SRC" ln -s "$SKILL_SRC" "$SKILL_TARGET"
else
  act "symlink $SKILL_TARGET -> $SKILL_SRC" ln -s "$SKILL_SRC" "$SKILL_TARGET"
fi

# 3. Symlink the rules file
if [ -L "$RULES_TARGET" ]; then
  # $1/$2 must expand inside the bash -c subshell, not the parent shell.
  # shellcheck disable=SC2016
  act "refresh symlink $RULES_TARGET -> $RULES_SRC" bash -c \
    'rm "$1" && ln -s "$2" "$1"' _ "$RULES_TARGET" "$RULES_SRC"
elif [ -e "$RULES_TARGET" ]; then
  log "WARNING: $RULES_TARGET exists and is not a symlink — backing up."
  act "backup $RULES_TARGET" mv "$RULES_TARGET" "$RULES_TARGET.bak.$TIMESTAMP"
  act "symlink $RULES_TARGET -> $RULES_SRC" ln -s "$RULES_SRC" "$RULES_TARGET"
else
  act "symlink $RULES_TARGET -> $RULES_SRC" ln -s "$RULES_SRC" "$RULES_TARGET"
fi

# 4. Mirror every directory under .claude/skills/ into ~/.gemini/skills/,
#    one at a time, so an existing non-symlink skill directory there is
#    never touched (same warn-and-skip behavior as scripts/install.sh's
#    equivalent .claude/skills loop for ~/.claude/skills/).
INSTALLED_GENERIC_SKILLS=()
for skill_src in "$CLAUDE_SKILLS_SRC_DIR"/*/; do
  skill_name="$(basename "$skill_src")"
  skill_target="$SKILLS_DIR/$skill_name"
  skill_src="${skill_src%/}"

  if [ -L "$skill_target" ]; then
    # $1/$2 must expand inside the bash -c subshell, not the parent shell.
    # shellcheck disable=SC2016
    act "refresh existing symlink $skill_target -> $skill_src" bash -c \
      'rm "$1" && ln -s "$2" "$1"' _ "$skill_target" "$skill_src"
    INSTALLED_GENERIC_SKILLS+=("$skill_name")
  elif [ -e "$skill_target" ]; then
    log "WARNING: $skill_target already exists and is not a symlink — skipping (not overwriting a real directory)."
  else
    act "symlink $skill_target -> $skill_src" ln -s "$skill_src" "$skill_target"
    INSTALLED_GENERIC_SKILLS+=("$skill_name")
  fi
done

# 5. Symlink each generated oc-<role> agent directory into
#    ~/.gemini/config/agents/, one at a time (same refresh/backup/create
#    idiom as the skill and rules symlinks above). Each must land as its own
#    dedicated subdirectory — Antigravity does not discover agent.md files
#    placed directly under ~/.gemini/config/agents/ (see antigravity/README.md).
INSTALLED_AGENTS=()
for agent_name in "${OC_AGENT_NAMES[@]}"; do
  agent_src="$AGENTS_SRC_DIR/$agent_name"
  agent_target="$AGENTS_DIR/$agent_name"

  if [ -L "$agent_target" ]; then
    # $1/$2 must expand inside the bash -c subshell, not the parent shell.
    # shellcheck disable=SC2016
    act "refresh existing symlink $agent_target -> $agent_src" bash -c \
      'rm "$1" && ln -s "$2" "$1"' _ "$agent_target" "$agent_src"
    INSTALLED_AGENTS+=("$agent_name")
  elif [ -e "$agent_target" ]; then
    log "WARNING: $agent_target already exists and is not a symlink — skipping (not overwriting a real directory)."
  else
    act "symlink $agent_target -> $agent_src" ln -s "$agent_src" "$agent_target"
    INSTALLED_AGENTS+=("$agent_name")
  fi
done

log ""
log "antigravity/install.sh: done (dry-run=$DRY_RUN)."
log ""
log "Installed:"
log "  skill:  $SKILL_TARGET -> $SKILL_SRC"
log "  rules:  $RULES_TARGET -> $RULES_SRC"
if [ "${#INSTALLED_GENERIC_SKILLS[@]}" -gt 0 ]; then
  log "  skills mirrored from .claude/skills/ into $SKILLS_DIR/:"
  for skill_name in "${INSTALLED_GENERIC_SKILLS[@]}"; do
    log "    - $skill_name"
  done
else
  log "  skills mirrored from .claude/skills/ into $SKILLS_DIR/: none found"
fi
if [ "${#INSTALLED_AGENTS[@]}" -gt 0 ]; then
  log "  agents symlinked from $AGENTS_SRC_DIR/ into $AGENTS_DIR/:"
  for agent_name in "${INSTALLED_AGENTS[@]}"; do
    log "    - $agent_name"
  done
else
  log "  agents symlinked from $AGENTS_SRC_DIR/ into $AGENTS_DIR/: none found"
fi
log ""
log "Workspace-scoped copies of the same six agents are also auto-discovered"
log "directly from $REPO_ROOT/.agents/agents/ (Antigravity walks up from CWD"
log "to the repo root) whenever you're working inside this repo — no install"
log "step needed for that. The symlinks above are for global availability"
log "across other projects."
log ""
log "Restart Antigravity (agy) for the agents to be available. Then confirm"
log "the six oc-* agents actually appear in the Antigravity app's /agents"
log "panel — that is the real acceptance check (see antigravity/README.md)."
